# frozen_string_literal: true

module AtlasRb
  # HTTP transport helpers shared by every resource class.
  #
  # Every Atlas request reads these environment variables:
  #
  # - `ATLAS_URL`   — base URL of the Atlas API (e.g. `https://atlas.example.edu`).
  # - `ATLAS_TOKEN` — Cerberus-relay bearer token used in the `Authorization`
  #   header on the default (relay) path.
  # - `ATLAS_JWT`   — *optional* personal-access JWT (minted by Atlas's
  #   `POST /nuid`, Cerberus-delegated post-SSO). When set, it switches the
  #   transport into **bring-your-own-JWT mode** (see below).
  #
  # ## Two transport modes
  #
  # **Relay mode (default, `ATLAS_JWT` unset).** Authenticates with
  # `ATLAS_TOKEN` and identifies the acting user via a `User: NUID <nuid>`
  # header, optionally an `On-Behalf-Of: NUID <nuid>` header for acting-as /
  # view-as flows. When `nuid` / `on_behalf_of` are omitted (positional arg
  # `nil`, kwarg `nil`), the helper falls through to {AtlasRb.config}'s
  # `default_nuid` / `default_on_behalf_of` callables — host applications wire
  # those up to their request-scoped `Current.*` source. Caller-passed values
  # always win over the configured defaults. This is the path Cerberus uses.
  #
  # **BYO-JWT mode (`ATLAS_JWT` set).** Authenticates with the JWT, which
  # already encodes the acting user — so **no `User:` header is sent**, and
  # `On-Behalf-Of` is **suppressed** (Atlas rejects acting-as on the JWT path
  # with a 403; acting-as is a relay-only concept). `ATLAS_JWT` takes
  # precedence over `ATLAS_TOKEN`. This is the standalone-script path: a
  # librarian exports their minted token and runs headless against the API.
  #
  # **Relay-signing mode ({AtlasRb.config#assertion_signing_key} set).** The
  # cryptographic replacement for the `ATLAS_TOKEN` relay: instead of a shared
  # secret + an asserted `User:` header, the regular relay path **signs** a
  # short-lived assertion (ES256, `iss=cerberus`, `aud=atlas`, `sub` = the
  # acting nuid) with Cerberus's private key — Atlas verifies it with the
  # public key. No `User:` header; identity is the proven `sub`. **Acting-as
  # auto-falls-back to the legacy relay**: an `on_behalf_of` request is NOT
  # signed (Atlas 403s `On-Behalf-Of` on the assertion path until a signed
  # `obo` claim ships), so the boundary cannot be violated by a caller. Off
  # unless a signing key is configured (so it coexists with `ATLAS_TOKEN`
  # during cutover). `ATLAS_JWT`, if set, still wins over signing.
  #
  # The module is mixed in via `extend`, so its methods become class methods on
  # the host (e.g. `AtlasRb::Work.connection({})`).
  module FaradayHelper
    # Wire contract Atlas enforces for relay-signing assertions (see Atlas
    # ApplicationController#verify_cerberus_assertion). iss/aud are fixed; the
    # short TTL bounds replay (Atlas allows 30s leeway on exp).
    ASSERTION_ISSUER   = "cerberus"
    ASSERTION_AUDIENCE = "atlas"
    ASSERTION_TTL      = 30 # seconds
    # Build a JSON-content Faraday connection to the Atlas API.
    #
    # @param params [Hash] query-string / body params to attach to the request.
    #   Resource classes use this to pass things like `parent_id:`, `work_id:`,
    #   or `metadata:` without manually serializing.
    # @param nuid [String, nil] optional Northeastern University ID to send in
    #   the `User` header. When `nil`, falls through to
    #   `AtlasRb.config.default_nuid&.call`; if that is also nil, no `User:`
    #   header is sent (legacy bearer-only path).
    # @param on_behalf_of [String, nil] optional NUID for the `On-Behalf-Of`
    #   header. When `nil`, falls through to
    #   `AtlasRb.config.default_on_behalf_of&.call`; if that is also nil, no
    #   `On-Behalf-Of:` header is sent. Used by acting-as / view-as flows.
    # @param idempotency_key [String, nil] optional UUID to send in the
    #   `Idempotency-Key` header. Used by retry-safe create flows (currently
    #   `POST /works`, `POST /file_sets`, `POST /files`) to deduplicate replays
    #   against the originally-created resource. Generated by the caller —
    #   this gem does not mint keys.
    # @return [Faraday::Connection] a connection that follows redirects and
    #   uses Faraday's default adapter.
    #
    # @example Fetching a community
    #   AtlasRb::Community.connection({}).get('/communities/abc123')
    def connection(params, nuid=nil, on_behalf_of: nil, idempotency_key: nil)
      headers = auth_headers(nuid, on_behalf_of).merge("Content-Type" => "application/json")
      headers["Idempotency-Key"] = idempotency_key if idempotency_key

      Faraday.new(
        url: ENV.fetch("ATLAS_URL", nil),
        params: params,
        headers: headers
      ) do |f|
        f.use AtlasRb::Middleware::RaiseOnStaleResource
        f.use AtlasRb::Middleware::RaiseOnResourceError
        f.response :follow_redirects
        f.adapter Faraday.default_adapter
      end
    end

    # Build a multipart Faraday connection used for binary and XML uploads.
    #
    # The same `ATLAS_URL` / `ATLAS_TOKEN` env vars apply. Unlike {#connection},
    # the `Content-Type` is set automatically by the multipart middleware, and
    # callers pass a payload hash whose values may include
    # `Faraday::Multipart::FilePart` instances. Fall-through semantics for
    # `nuid` / `on_behalf_of` match {#connection}.
    #
    # @param nuid [String, nil] optional NUID for the `User` header.
    # @param on_behalf_of [String, nil] optional NUID for the `On-Behalf-Of`
    #   header.
    # @param idempotency_key [String, nil] optional UUID to send in the
    #   `Idempotency-Key` header. See {#connection} for semantics; the
    #   `POST /files` (Blob) create flow uses this transport.
    # @return [Faraday::Connection] a multipart-aware connection.
    #
    # @example Posting a binary blob
    #   payload = {
    #     work_id: "w-123",
    #     binary: Faraday::Multipart::FilePart.new(File.open("scan.pdf"),
    #                                               "application/octet-stream",
    #                                               "scan.pdf")
    #   }
    #   AtlasRb::Blob.multipart.post('/files/', payload)
    def multipart(nuid=nil, on_behalf_of: nil, idempotency_key: nil)
      headers = auth_headers(nuid, on_behalf_of)
      headers["Idempotency-Key"] = idempotency_key if idempotency_key

      Faraday.new(
        url: ENV.fetch("ATLAS_URL", nil),
        headers: headers
      ) do |f|
        f.use AtlasRb::Middleware::RaiseOnStaleResource
        f.request :multipart
        f.request :url_encoded
      end
    end

    # Build a Faraday connection authenticated as the Atlas `:system`
    # fixture for system-context calls (SSO user provisioning, etc.).
    #
    # **Distinct from {#connection}.** The bearer token comes from
    # `Rails.application.credentials.atlas_system_token` (NOT `ENV` — the
    # source report's leak-halving argument: a `.env` leak shouldn't
    # expose the system token alongside the user token). The `User:`
    # header is hard-pinned to {AtlasRb::System::NUID} so this path
    # always identifies as the Atlas system principal. The configurable
    # `default_nuid` / `default_on_behalf_of` are **never** consulted —
    # there is no ambient user context on this path.
    #
    # Used exclusively by classes under {AtlasRb::System}.
    #
    # @param params [Hash] query-string / body params.
    # @return [Faraday::Connection] a system-authenticated connection.
    # @raise [RuntimeError] if the credential is not configured.
    # @raise [NameError] if `Rails` is not loaded (the gem assumes a
    #   Rails host for system-path calls).
    def system_connection(params = {})
      token = Rails.application.credentials.atlas_system_token ||
              raise("atlas_rb: Rails.application.credentials.atlas_system_token not configured")

      headers = {
        "Content-Type"  => "application/json",
        "Authorization" => "Bearer #{token}",
        "User"          => "NUID #{AtlasRb::System::NUID}"
      }

      Faraday.new(
        url: ENV.fetch("ATLAS_URL", nil),
        params: params,
        headers: headers
      ) do |f|
        f.response :follow_redirects
        f.adapter Faraday.default_adapter
      end
    end

    private

    # Build the auth + identity headers shared by {#connection} and {#multipart}.
    # Precedence: ATLAS_JWT (BYO-JWT) > relay-signing > ATLAS_TOKEN relay. The
    # acting nuid / on_behalf_of fall through to the configured `default_nuid` /
    # `default_on_behalf_of` callables here, once, for whichever mode applies.
    def auth_headers(nuid, on_behalf_of)
      jwt = ENV.fetch("ATLAS_JWT", nil)
      return { "Authorization" => "Bearer #{jwt}" } if jwt

      nuid         ||= AtlasRb.config.default_nuid&.call
      on_behalf_of ||= AtlasRb.config.default_on_behalf_of&.call

      signed_relay_headers(nuid, on_behalf_of) || relay_headers(nuid, on_behalf_of)
    end

    # A signed-assertion Authorization header (sub = acting nuid), or nil to
    # defer to the legacy relay. nil when signing isn't configured, there is no
    # acting nuid to put in `sub`, or this is an acting-as request — On-Behalf-Of
    # stays on the cerberus_token relay (Atlas 403s it on the assertion path),
    # so the boundary can't be violated by a caller.
    def signed_relay_headers(nuid, on_behalf_of)
      return nil unless nuid && on_behalf_of.nil?

      key = assertion_signing_key
      return nil unless key

      { "Authorization" => "Bearer #{signed_assertion(nuid.to_s, key)}" }
    end

    # Legacy relay headers: ATLAS_TOKEN bearer + acting-user identity headers.
    # `nuid` / `on_behalf_of` are already resolved by {#auth_headers}.
    def relay_headers(nuid, on_behalf_of)
      headers = { "Authorization" => "Bearer #{ENV.fetch("ATLAS_TOKEN", nil)}" }
      headers["User"]         = "NUID #{nuid}" if nuid
      headers["On-Behalf-Of"] = "NUID #{on_behalf_of}" if on_behalf_of
      headers
    end

    # Mint a Cerberus relay assertion for `nuid`, signed ES256 with `key`. The
    # `kid` header tells Atlas which public key to verify against; iss/aud are
    # the fixed contract; the short TTL bounds replay; `jti` is forward-compat
    # for an Atlas-side one-time cache.
    def signed_assertion(nuid, key)
      now = Time.now.to_i
      payload = {
        "iss" => ASSERTION_ISSUER,
        "aud" => ASSERTION_AUDIENCE,
        "sub" => nuid,
        "iat" => now,
        "exp" => now + ASSERTION_TTL,
        "jti" => SecureRandom.uuid
      }
      JWT.encode(payload, key, "ES256", { kid: assertion_signing_kid })
    end

    # Resolve the configured signing key to an OpenSSL::PKey, or nil if signing
    # is not configured. Accepts a callable (resolved per request), a PEM
    # string (parsed), or an already-built key.
    def assertion_signing_key
      raw = config_value(AtlasRb.config.assertion_signing_key)
      return nil if raw.nil?

      raw.is_a?(OpenSSL::PKey::PKey) ? raw : OpenSSL::PKey.read(raw)
    end

    def assertion_signing_kid
      config_value(AtlasRb.config.assertion_signing_kid)
    end

    # Config slots may hold a value or a callable resolved at request time.
    def config_value(value)
      value.respond_to?(:call) ? value.call : value
    end
  end
end
